### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [JonathanReeve/annotags#5]
I'm reading actual books again :smile_cat: :book: and remembered this project and wanted to use it and iterate on it.

Would you mind adding a `LICENSE` file to it or some comments in the headers?

MIT or Apache seem like a good fit, but it's your code. :wink:

Right now, though, it's technically All Rights Reserved...at least in the USofA.

Thanks!
:tophat:

**Comment by JonathanReeve** [comment]
Good idea. Will add one ASAP.

**Comment by JonathanReeve** [comment]
Just added the GPLv3. Feel free to hack away on it and submit a PR!
